/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './src/routes/__root'
import { Route as EmployeeRouteImport } from './src/routes/employee'
import { Route as AdminRouteImport } from './src/routes/admin'
import { Route as IndexRouteImport } from './src/routes/index'
import { Route as EmployeeIndexRouteImport } from './src/routes/employee.index'
import { Route as EmployeeProfileRouteImport } from './src/routes/employee.profile'
import { Route as EmployeeCheckinRouteImport } from './src/routes/employee.checkin'

const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeCheckinRoute = EmployeeCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => EmployeeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/employee/checkin': typeof EmployeeCheckinRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/': typeof EmployeeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/employee/checkin': typeof EmployeeCheckinRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee': typeof EmployeeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/employee/checkin': typeof EmployeeCheckinRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/': typeof EmployeeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/employee'
    | '/employee/checkin'
    | '/employee/profile'
    | '/employee/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/employee/checkin' | '/employee/profile' | '/employee'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/employee'
    | '/employee/checkin'
    | '/employee/profile'
    | '/employee/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EmployeeRoute: typeof EmployeeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/profile': {
      id: '/employee/profile'
      path: '/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/checkin': {
      id: '/employee/checkin'
      path: '/checkin'
      fullPath: '/employee/checkin'
      preLoaderRoute: typeof EmployeeCheckinRouteImport
      parentRoute: typeof EmployeeRoute
    }
  }
}

interface EmployeeRouteChildren {
  EmployeeCheckinRoute: typeof EmployeeCheckinRoute
  EmployeeProfileRoute: typeof EmployeeProfileRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeCheckinRoute: EmployeeCheckinRoute,
  EmployeeProfileRoute: EmployeeProfileRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EmployeeRoute: EmployeeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './src/router.tsx'
import type { startInstance } from './src/start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
